const positive=new Set('love loved lovely amazing great excellent beautiful helpful awesome good fantastic perfect recommend wonderful happy thanks thank brilliant useful impressive best satisfied'.split(' '));
const negative=new Set('hate hated bad awful terrible disappointed disappointing broken slow worst useless poor expensive confusing rude scam unhappy difficult problem problems fail failed annoying'.split(' '));
export function sentiment(text=''){const words=text.toLowerCase().match(/[a-z]+/g)||[];let score=0;words.forEach((word,i)=>{let value=positive.has(word)?1:negative.has(word)?-1:0;if(value&&words.slice(Math.max(0,i-3),i).some(w=>['not','never','no','isnt','wasnt'].includes(w)))value*=-1;score+=value;});return {label:score>0?'positive':score<0?'negative':'neutral',score};}
export const interactions=p=>['likes','commentsCount','shares','saves'].reduce((sum,k)=>sum+(Number(p[k])||0),0);
export function postingBucket(date,timezone){const parts=new Intl.DateTimeFormat('en-US',{timeZone:timezone,weekday:'short',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date(date));return {day:parts.find(p=>p.type==='weekday').value,hour:Number(parts.find(p=>p.type==='hour').value)};}
const median=values=>{const a=[...values].sort((a,b)=>a-b),i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2;};
export function analyze(posts,comments,timezone='Asia/Karachi'){
 const total=posts.reduce((s,p)=>s+interactions(p),0),eligible=posts.filter(p=>Number.isFinite(p.reach)&&p.reach>0),reach=eligible.reduce((s,p)=>s+p.reach,0),rate=reach?eligible.reduce((s,p)=>s+interactions(p),0)/reach*100:null;
 const daily={},formats={},slots={},sentimentCounts={positive:0,neutral:0,negative:0},sentimentDays={};
 for(const p of posts){const date=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(p.publishedAt));daily[date]??={date,interactions:0,posts:0,reach:0};daily[date].interactions+=interactions(p);daily[date].posts++;daily[date].reach+=p.reach||0;formats[p.format]??={format:p.format,count:0,total:0};formats[p.format].count++;formats[p.format].total+=interactions(p);if(p.reach>0){const {day,hour}=postingBucket(p.publishedAt,timezone),bucket=Math.floor(hour/3)*3,k=day+'-'+bucket;slots[k]??={day,hour:bucket,rates:[]};slots[k].rates.push(interactions(p)/p.reach*100);}}
 const classified=comments.map(c=>({...c,sentiment:sentiment(c.text).label}));for(const c of classified){sentimentCounts[c.sentiment]++;const date=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(c.publishedAt));sentimentDays[date]??={date,positive:0,neutral:0,negative:0};sentimentDays[date][c.sentiment]++;}
 const times=Object.values(slots).map(s=>({day:s.day,hour:s.hour,count:s.rates.length,rate:median(s.rates)})).sort((a,b)=>b.rate-a.rate),qualified=times.filter(s=>s.count>=3),top=posts.map(p=>({...p,interactions:interactions(p),engagementRate:p.reach>0?interactions(p)/p.reach*100:null})).sort((a,b)=>b.interactions-a.interactions);
 const insights=[];if(qualified.length){const t=qualified[0];insights.push({type:'timing',title:`Test ${t.day}, ${String(t.hour).padStart(2,'0')}:00–${String(t.hour+3).padStart(2,'0')}:00`,detail:`${t.rate.toFixed(2)}% median engagement rate across ${t.count} posts. This is a historical association, not a guaranteed best time.`});}else insights.push({type:'timing',title:'Build a stronger timing sample',detail:'At least 3 posts with reach data in the same weekday and 3-hour window are needed for a posting-time recommendation.'});
 const leading=Object.values(formats).filter(f=>f.count>=3).sort((a,b)=>b.total/b.count-a.total/a.count)[0];if(leading)insights.push({type:'content',title:`${leading.format} leads average interactions`,detail:`${Math.round(leading.total/leading.count)} interactions per post across ${leading.count} posts. Older posts have had more time to accumulate engagement.`});
 if(comments.length)insights.push({type:'sentiment',title:`${Math.round(sentimentCounts.negative/comments.length*100)}% of sampled comments flagged negative`,detail:`Based on ${comments.length} fetched comments. English keyword scoring needs human review; it may miss sarcasm and other languages.`});
 if(posts.length&&!eligible.length)insights.push({type:'coverage',title:'Reach metrics are unavailable',detail:'Engagement counts remain available, but reach-based rates cannot be calculated. Check account permissions and API metric support.'});
 return {summary:{posts:posts.length,interactions:total,reach:eligible.length?reach:null,engagementRate:rate,reachCoverage:posts.length?eligible.length/posts.length*100:0,comments:comments.length},daily:Object.values(daily).sort((a,b)=>a.date.localeCompare(b.date)),formats:Object.values(formats).map(f=>({...f,average:Math.round(f.total/f.count)})),times,insights,posts:top,comments:classified,sentiment:sentimentCounts,sentimentTrend:Object.values(sentimentDays).sort((a,b)=>a.date.localeCompare(b.date))};
}
