import express from 'express';import cookieParser from 'cookie-parser';import helmet from 'helmet';import rateLimit from 'express-rate-limit';import mongoose from 'mongoose';import {z} from 'zod';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
import {User,Session,Workspace,Account,Post,Comment,OAuthState,PendingConnection,Report} from './models.js';import {passwordHash,passwordMatches,randomToken,hash,encrypt,decrypt} from './security.js';import {analyze} from './analytics.js';import {metaConfiguration} from './meta-config.js';import {liveAccounts,liveReports,reportingFilters} from './live-data.js';import {graph,apiVersion,discoverAccounts,syncAccount} from './meta.js';
const app=express();app.use(helmet({contentSecurityPolicy:{directives:{'img-src':["'self'",'data:','https:'],'style-src':["'self'","'unsafe-inline'"]}}}));app.use(express.json({limit:'100kb'}));app.use(cookieParser());app.use('/api',rateLimit({windowMs:60000,limit:300,standardHeaders:true,legacyHeaders:false}));
const fail=(status,message)=>Object.assign(new Error(message),{status});const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);const oid=value=>{if(typeof value!=='string'||!/^[a-f0-9]{24}$/i.test(value))throw fail(400,'Invalid resource ID.');return value;};
const cookieOptions=()=>({httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:7*86400000});
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)){if(!req.is('application/json'))return res.status(415).json({error:'JSON required.'});if(req.headers.origin&&new URL(req.headers.origin).origin!==new URL(process.env.APP_URL||'http://localhost:5173').origin)return res.status(403).json({error:'Origin is not allowed.'});}next();});
const auth=wrap(async(req,res,next)=>{const token=req.cookies.pulse_session;if(!token)throw fail(401,'Please sign in.');const session=await Session.findOne({tokenHash:hash(token),expiresAt:{$gt:new Date()}});if(!session)throw fail(401,'Session expired. Please sign in.');req.user=await User.findById(session.userId);if(!req.user)throw fail(401,'Account not found.');next();});
const access=wrap(async(req,res,next)=>{req.workspace=await Workspace.findOne({_id:oid(req.params.workspaceId),'members.userId':req.user._id});if(!req.workspace)throw fail(403,'Workspace access denied.');req.role=req.workspace.members.find(m=>String(m.userId)===String(req.user._id)).role;next();});const edit=(req,res,next)=>req.role==='viewer'?next(fail(403,'Viewers cannot change this workspace.')):next();const owner=(req,res,next)=>req.role==='owner'?next():next(fail(403,'Only the workspace owner can perform this action.'));
async function login(res,user){const token=randomToken();await Session.create({tokenHash:hash(token),userId:user._id,expiresAt:new Date(Date.now()+7*86400000)});res.cookie('pulse_session',token,cookieOptions());}
app.get('/api/health',(req,res)=>res.json({ok:mongoose.connection.readyState===1,service:'ORVYN Pulse'}));
const authLimit=rateLimit({windowMs:15*60000,limit:30,standardHeaders:true,legacyHeaders:false});
app.post('/api/auth/register',authLimit,wrap(async(req,res)=>{const input=z.object({name:z.string().trim().min(2).max(80),email:z.string().email().max(180),password:z.string().min(10).max(128)}).parse(req.body);const email=input.email.toLowerCase();if(await User.exists({email}))throw fail(409,'This email is already registered.');const user=await User.create({name:input.name,email,passwordHash:await passwordHash(input.password)});await Workspace.create({name:input.name+'’s workspace',owner:user._id,members:[{userId:user._id,role:'owner'}]});await login(res,user);res.status(201).json({user:{id:user.id,name:user.name,email:user.email}});}));
app.post('/api/auth/login',authLimit,wrap(async(req,res)=>{const input=z.object({email:z.string().email(),password:z.string().max(128)}).parse(req.body);const user=await User.findOne({email:input.email.toLowerCase()}).select('+passwordHash');if(!user||!await passwordMatches(input.password,user.passwordHash))throw fail(401,'Incorrect email or password.');await login(res,user);res.json({user:{id:user.id,name:user.name,email:user.email}});}));
app.post('/api/auth/logout',auth,wrap(async(req,res)=>{await Session.deleteOne({tokenHash:hash(req.cookies.pulse_session)});res.clearCookie('pulse_session',{...cookieOptions(),maxAge:undefined});res.json({ok:true});}));
app.get('/api/auth/me',auth,(req,res)=>res.json({user:{id:req.user.id,name:req.user.name,email:req.user.email}}));
app.get('/api/workspaces',auth,wrap(async(req,res)=>res.json(await Workspace.find({'members.userId':req.user._id}).lean())));
app.post('/api/workspaces',auth,wrap(async(req,res)=>{const input=z.object({name:z.string().trim().min(2).max(80),timezone:z.string().default('Asia/Karachi')}).parse(req.body);try{new Intl.DateTimeFormat('en',{timeZone:input.timezone});}catch{throw fail(400,'Invalid timezone.');}if(await Workspace.countDocuments({owner:req.user._id})>=10)throw fail(400,'You can own up to 10 workspaces.');res.status(201).json(await Workspace.create({...input,owner:req.user._id,members:[{userId:req.user._id,role:'owner'}]}));}));
const router=express.Router({mergeParams:true});app.use('/api/workspaces/:workspaceId',auth,access,router);
router.get('/accounts',wrap(async(req,res)=>res.json(await Account.find(liveAccounts(req.workspace._id)).lean())));
router.delete('/accounts/:accountId',owner,wrap(async(req,res)=>{const a=await Account.findOneAndDelete({_id:oid(req.params.accountId),...liveAccounts(req.workspace._id)});if(!a)throw fail(404,'Account not found.');await Promise.all([Post.deleteMany({accountId:a._id}),Comment.deleteMany({accountId:a._id})]);res.json({ok:true});}));
router.post('/accounts/:accountId/sync',edit,wrap(async(req,res)=>{const a=await Account.findOne({_id:oid(req.params.accountId),...liveAccounts(req.workspace._id)});if(!a)throw fail(404,'Account not found.');void syncAccount(a._id).catch(()=>console.error('Manual sync failed',a.id));res.status(202).json({message:'Synchronization started. Account status will update as records are imported.'});}));
async function analytics(req){const days=z.coerce.number().int().min(7).max(90).default(30).parse(req.query.days),source=reportingFilters(req.workspace._id,req.query).source,platform=z.enum(['all','instagram','facebook']).default('all').parse(req.query.platform);const end=new Date(),start=new Date(end.getTime()-days*86400000),filter={workspaceId:req.workspace._id,source,publishedAt:{$gte:start,$lte:end},...(platform!=='all'?{platform}:{})};const accounts=await Account.find({workspaceId:req.workspace._id,source,...(platform!=='all'?{platform}:{})}).select('_id');const [posts,comments]=await Promise.all([Post.find({...filter,accountId:{$in:accounts.map(a=>a._id)}}).limit(10000).lean(),Comment.find({workspaceId:req.workspace._id,source,accountId:{$in:accounts.map(a=>a._id)},publishedAt:{$gte:start,$lte:end}}).limit(20000).lean()]);return {...analyze(posts,comments,req.workspace.timezone),filters:{days,source,platform,timezone:req.workspace.timezone,from:start,to:end},generatedAt:end};}
router.get('/analytics',wrap(async(req,res)=>res.json(await analytics(req))));
router.get('/reports',wrap(async(req,res)=>res.json(await Report.find(liveReports(req.workspace._id)).select('-data').sort({createdAt:-1}).limit(50).lean())));
router.post('/reports',edit,wrap(async(req,res)=>{const data=await analytics(req);if(!data.summary.posts)throw fail(400,'Synchronize an account with posts in this date range before saving a report.');res.status(201).json(await Report.create({workspaceId:req.workspace._id,createdBy:req.user._id,title:z.string().trim().min(1).max(100).parse(req.body.title),filters:data.filters,data}));}));
router.get('/reports/:reportId',wrap(async(req,res)=>{const r=await Report.findOne({_id:oid(req.params.reportId),...liveReports(req.workspace._id)}).lean();if(!r)throw fail(404,'Report not found.');res.json(r);}));
router.get('/members',wrap(async(req,res)=>{const ws=await Workspace.findById(req.workspace._id).populate('members.userId','name email');res.json(ws.members);}));
router.post('/members',owner,wrap(async(req,res)=>{const input=z.object({email:z.string().email(),role:z.enum(['analyst','viewer'])}).parse(req.body),u=await User.findOne({email:input.email.toLowerCase()});if(!u)throw fail(404,'Ask this teammate to register first, then add their email. No message is sent.');const result=await Workspace.updateOne({_id:req.workspace._id,'members.userId':{$ne:u._id}},{$push:{members:{userId:u._id,role:input.role}}});if(!result.modifiedCount)throw fail(409,'This person is already a member.');res.json({ok:true});}));
router.delete('/members/:userId',owner,wrap(async(req,res)=>{if(req.params.userId===String(req.workspace.owner))throw fail(400,'The owner cannot be removed.');await Workspace.updateOne({_id:req.workspace._id},{$pull:{members:{userId:oid(req.params.userId)}}});res.json({ok:true});}));
router.get('/meta/status',(req,res)=>{const c=metaConfiguration();res.json(req.role==='owner'?c:{configured:c.configured,version:c.version});});
router.post('/meta/connect',owner,wrap(async(req,res)=>{const config=metaConfiguration();if(!config.configured)throw fail(503,'Complete Meta setup: '+config.checks.filter(c=>!c.ready).map(c=>c.key).join(', '));encrypt('configuration-check');const state=randomToken();await OAuthState.create({stateHash:hash(state),userId:req.user._id,workspaceId:req.workspace._id,expiresAt:new Date(Date.now()+10*60000)});const url=new URL(`https://www.facebook.com/${apiVersion()}/dialog/oauth`);url.searchParams.set('client_id',process.env.META_APP_ID);url.searchParams.set('redirect_uri',process.env.META_REDIRECT_URI);url.searchParams.set('state',state);url.searchParams.set('response_type','code');url.searchParams.set('auth_type','rerequest');if(process.env.META_LOGIN_CONFIG_ID)url.searchParams.set('config_id',process.env.META_LOGIN_CONFIG_ID);url.searchParams.set('scope',process.env.META_SCOPES||'pages_show_list,pages_read_engagement,read_insights,instagram_basic,instagram_manage_insights,instagram_manage_comments');res.json({url:String(url)});}));
app.get('/api/meta/callback',wrap(async(req,res)=>{
 const target=new URL(process.env.APP_URL || 'http://localhost:5173');
 const redirectError=message=>{target.searchParams.set('connection','error');target.searchParams.set('message',message);return res.redirect(target.toString());};
 try {
  const token=req.cookies.pulse_session;
  const session=token&&await Session.findOne({tokenHash:hash(token),expiresAt:{$gt:new Date()}});
  if(!session)return redirectError('Sign in again, then restart the Meta connection.');
  const state=z.string().min(20).max(100).parse(req.query.state);
  const saved=await OAuthState.findOneAndDelete({stateHash:hash(state),userId:session.userId,expiresAt:{$gt:new Date()}});
  if(!saved)return redirectError('Connection session expired. Start Connect with Meta again.');
  const ws=await Workspace.findOne({_id:saved.workspaceId,owner:session.userId});
  if(!ws)return redirectError('Workspace ownership changed. Ask its owner to connect.');
  target.searchParams.set('workspace',ws.id);
  if(req.query.error){target.searchParams.set('connection','cancelled');return res.redirect(target.toString());}
  const code=z.string().min(1).max(4000).parse(req.query.code);
  const short=await graph('oauth/access_token',null,{client_id:process.env.META_APP_ID,client_secret:process.env.META_APP_SECRET,redirect_uri:process.env.META_REDIRECT_URI,code});
  const long=await graph('oauth/access_token',null,{grant_type:'fb_exchange_token',client_id:process.env.META_APP_ID,client_secret:process.env.META_APP_SECRET,fb_exchange_token:short.access_token});
  const {accounts:candidates,warnings}=await discoverAccounts(long.access_token);
  if(!candidates.length)return redirectError('No eligible Pages were returned. Check your Facebook Page access and grant Page permissions during authorization.');
  const pending=await PendingConnection.create({userId:session.userId,workspaceId:ws._id,candidates:encrypt(candidates),warnings,expiresAt:new Date(Date.now()+10*60000)});
  target.searchParams.set('connect',pending.id);res.redirect(target.toString());
 } catch(e) {return redirectError(e.metaCode!==undefined?e.message:'Meta connection could not finish. Check app credentials and the registered callback, then try again.');}
}));
router.get('/meta/pending/:pendingId',owner,wrap(async(req,res)=>{const p=await PendingConnection.findOne({_id:oid(req.params.pendingId),workspaceId:req.workspace._id,userId:req.user._id,expiresAt:{$gt:new Date()}}).select('+candidates');if(!p)throw fail(404,'Connection selection expired. Connect again.');res.json({accounts:decrypt(p.candidates).map(({token,...rest})=>rest),warnings:p.warnings||[]});}));
router.post('/meta/pending/:pendingId',owner,wrap(async(req,res)=>{const ids=z.array(z.string()).min(1).max(10).parse(req.body.accounts);const p=await PendingConnection.findOne({_id:oid(req.params.pendingId),workspaceId:req.workspace._id,userId:req.user._id,expiresAt:{$gt:new Date()}}).select('+candidates');if(!p)throw fail(404,'Connection selection expired.');const candidates=decrypt(p.candidates),selected=candidates.filter(a=>ids.includes(a.platform+':'+a.remoteId));if(selected.length!==new Set(ids).size)throw fail(400,'Invalid account selection.');const existing=await Account.countDocuments({workspaceId:req.workspace._id,source:'live'});const newCount=await Promise.all(selected.map(a=>Account.exists({workspaceId:req.workspace._id,platform:a.platform,remoteId:a.remoteId})));if(existing+newCount.filter(x=>!x).length>10)throw fail(400,'Student workspaces support 10 connected accounts.');for(const c of selected){const a=await Account.findOneAndUpdate({workspaceId:req.workspace._id,platform:c.platform,remoteId:c.remoteId},{$set:{...c,token:encrypt(c.token),source:'live',status:'connected',lastError:null}},{upsert:true,new:true});void syncAccount(a._id).catch(()=>console.error('Initial sync failed',a.id));}await p.deleteOne();res.json({connected:selected.length});}));
const dist=resolve(dirname(fileURLToPath(import.meta.url)),'../..','client/dist');app.use(express.static(dist));app.get('/{*path}',(req,res,next)=>req.path.startsWith('/api/')?res.status(404).json({error:'Endpoint not found.'}):res.sendFile(resolve(dist,'index.html'),e=>e&&next(e)));
app.use((err,req,res,next)=>{if(err instanceof z.ZodError)return res.status(400).json({error:err.issues[0]?.message||'Invalid input.'});const status=err.status|| (err.code===11000?409:500);if(status===500)console.error('Request failed:',err.name);res.status(status).json({error:status===500?'The request could not finish. Check server configuration and try again.':err.code===11000?'This record already exists.':err.message});});
export default app;
